# .github/workflows/main.yml
name: MLOps API CI/CD Local

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ml-api-cancer:${{ github.sha }} .

      - name: Run Docker container (Background)
        run: docker run -d -p 5000:5000 --name ml-api-test ml-api-cancer:${{ github.sha }}

      - name: Wait for API to start (10 seconds)
        run: sleep 10

      - name: Test API Root Endpoint (Health Check)
        run: |
          # Intenta consultar el endpoint varias veces si falla
          for i in 1 2 3 4 5; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
            if [ "$RESPONSE" = "200" ]; then
              echo "✅ API Health Check passed (Status 200)"
              exit 0
            fi
            echo "Attempt $i failed with status $RESPONSE. Retrying..."
            sleep 2
          done
          echo "❌ API failed to respond after multiple retries."
          exit 1
      
      - name: Test Prediction Endpoint (Data Check)
        run: |
          # Datos de prueba para un caso (maligno)
          PREDICT_DATA='[17.99, 10.38, 122.8, 1001.0, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 
          8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019.0, 0.1622, 0.6656, 
          0.7119, 0.2654, 0.4601, 0.1189]'
          
          # Realizar la solicitud POST
          RESPONSE=$(curl -X POST \
             -H "Content-Type: application/json" \
             -d "{\"features\": ${PREDICT_DATA}}" \
             http://localhost:5000/predict)
             
          # Verificar que la respuesta contenga "malignant" o "benign"
          if echo "$RESPONSE" | grep -q "prediction"; then
            echo "✅ API Prediction Test passed. Response: $RESPONSE"
          else
            echo "❌ API Prediction Test failed. Unexpected response: $RESPONSE"
            exit 1
          fi
          
      - name: Cleanup Container
        if: always()
        run: docker stop ml-api-test && docker rm ml-api-test
